---

# apt-cache show elasticsearch
#
# Could check the version with:
# aptitude search elasticsearch -F "%V"
# aptitude search elasticsearch -F "%c %V %p %d"
- apt: name=elasticsearch=1.6.0 state=absent purge=yes
  ignore_errors: yes

- apt_repository: repo="deb http://packages.elastic.co/elasticsearch/1.6/debian stable main"
  args:
    state: absent
    update_cache: yes
